<?php
$fixedSequential = [
    ['INTRODUÇÃO À EAD', '80h'],
    ['EMPREENDEDORISMO', '80h'],
    ['PLANEJAMENTO ESTRATÉGICO', '80h'],
    ['FUNDAMENTOS DA ADMINISTRAÇÃO', '80h'],
];

$sequentialArea = function (string $slug, string $title): string {
    $key = $slug . ' ' . mb_strtolower($title, 'UTF-8');
    if (str_contains($key, 'hospitalar') || str_contains($key, 'laboratorios') || str_contains($key, 'laboratórios') || str_contains($key, 'farmacias') || str_contains($key, 'farmácias')) return 'Saúde';
    if (str_contains($key, 'meio-ambiente')) return 'Meio ambiente e agropecuária';
    if (str_contains($key, 'informatica') || str_contains($key, 'informática') || str_contains($key, 'design') || str_contains($key, 'midias-digitais') || str_contains($key, 'mídias digitais')) return 'Tecnologia e informática';
    if (str_contains($key, 'educacional') || str_contains($key, 'pedagogica') || str_contains($key, 'pedagógica')) return 'Educação';
    if (str_contains($key, 'construcao') || str_contains($key, 'construção')) return 'Construção e infraestrutura';
    if (str_contains($key, 'oficinas-mecanicas') || str_contains($key, 'oficinas mecânicas')) return 'Engenharia e manutenção';
    if (str_contains($key, 'seguranca') || str_contains($key, 'segurança')) return 'Segurança';
    if (str_contains($key, 'futebol') || str_contains($key, 'arbitragem') || str_contains($key, 'esportiva') || str_contains($key, 'religiosas')) return 'Serviços';
    return 'Administração e gestão';
};

$seq = function (int $id, string $slug, string $title, string $description, string $selectives) use ($fixedSequential, $sequentialArea): array {
    $selectiveItems = array_map(
        fn($subject) => [trim($subject), '80h'],
        array_filter(explode('|', $selectives), fn($subject) => trim($subject) !== '')
    );
    return [
        'id' => $id,
        'slug' => $slug,
        'title' => $title,
        'category' => 'Superior Sequencial',
        'area' => $sequentialArea($slug, $title),
        'price' => 699.00,
        'currency' => 'BRL',
        'checkout_enabled' => 1,
        'status' => 'active',
        'duration' => '06 meses',
        'workload' => '560 horas',
        'short_description' => $title . '. Curso Superior Sequencial de Complementação de Estudos, 100% EAD, com matriz curricular oficial de 560 horas.',
        'description' => $description,
        'seo_title' => $title . ' | IBETP',
        'seo_description' => 'Conheça o ' . $title . ' do IBETP: curso Superior Sequencial 100% EAD, matriz curricular oficial, documentação, investimento e matrícula.',
        'updated_at' => '2026-07-21 00:00:00',
        'academic' => [
            'duration' => '06 meses',
            'workload' => '560 horas',
            'modality_note' => 'Curso Superior Sequencial de Complementação de Estudos, 100% EAD.',
            'presence' => 'Modalidade 100% EAD conforme informativo oficial do curso.',
            'internship' => 'O informativo acadêmico analisado não informa estágio obrigatório para este curso.',
            'tcc' => 'O informativo acadêmico analisado não informa TCC obrigatório.',
            'source' => 'Grade oficial extraída do informativo do curso.',
            'modules' => [
                ['Módulo I — Disciplinas fixas', '320h', $fixedSequential],
                ['Módulo II — Disciplinas seletivas', 'Escolha de 3 disciplinas, totalizando 240h', $selectiveItems],
            ],
        ],
    ];
};

return [
    $seq(-9901, 'superior-sequencial-em-gestao-publica', 'Superior Sequencial em Gestão Pública', 'Formação voltada ao planejamento e à gestão estratégica no setor público, com foco em políticas públicas, gestão de resultados, projetos, orçamento e processos administrativos.', 'ANÁLISE E MODELAGEM DE PROCESSOS|GESTÃO DA QUALIDADE|GESTÃO DA TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO|GESTÃO DE PROJETOS|LICITAÇÕES PÚBLICAS|ANÁLISE DA VIABILIDADE ECONÔMICA E FINANCEIRA DE PROJETOS|GESTÃO DE RISCOS|LIDERANÇA E DESENVOLVIMENTO DE EQUIPES|PROCESSO DECISÓRIO|PLANEJAMENTO ESTRATÉGICO|SISTEMAS DE INFORMAÇÕES GERENCIAIS|TÓPICOS DE ECONOMIA|CONTABILIDADE PÚBLICA|GESTÃO DE POLÍTICAS PÚBLICAS|ORÇAMENTO E FINANÇAS PÚBLICAS'),
    $seq(-9902, 'superior-sequencial-em-gestao-do-meio-ambiente', 'Superior Sequencial em Gestão do Meio Ambiente', 'Formação voltada à interação entre sociedade, organizações e meio ambiente, com foco em gestão ambiental, resíduos, recursos naturais, qualidade ambiental e sustentabilidade.', 'DIREITO AMBIENTAL|GESTÃO AMBIENTAL|HIGIENE E VIGILÂNCIA SANITÁRIA|LOGÍSTICA REVERSA|TRATAMENTO DA ÁGUA E EFLUENTES|BIOESTATÍSTICA|COMBATE E PREVENÇÃO DE INCÊNDIOS E PÂNICOS|GESTÃO DE RECURSOS HUMANOS|MICROBIOLOGIA APLICADA AO MEIO AMBIENTE|QUALIDADE DO AR|BIOÉTICA E BIOSSEGURANÇA|CARTOGRAFIA E GEOPROCESSAMENTO|EDUCAÇÃO AMBIENTAL|QUALIDADE DO SOLO E RECUPERAÇÃO DE ÁREAS DEGRADADAS|TRATAMENTO DE RESÍDUOS SÓLIDOS'),
    $seq(-9903, 'superior-sequencial-em-gestao-em-logistica', 'Superior Sequencial em Gestão em Logística', 'Formação voltada à gestão de processos logísticos, armazenagem, transportes, negociação, suprimentos e cadeia de suprimentos.', 'GESTÃO DE COMPRAS E NEGOCIAÇÃO|GESTÃO DE LOGÍSTICA DE ARMAZENAGEM|GESTÃO DE LOGÍSTICA DE TRANSPORTES|GESTÃO DE LOGÍSTICA INTERNACIONAL|GESTÃO DE LOGÍSTICA REVERSA|GESTÃO DE AUDITORIA DA QUALIDADE|GESTÃO DE ECONOMIA E MERCADO GLOBAL|GESTÃO DE GESTÃO DE RECURSOS HUMANOS|GESTÃO DE ÉTICA E CIDADANIA|GESTÃO DE GESTÃO DA PRODUÇÃO|GESTÃO DE GESTÃO DA QUALIDADE|GESTÃO DE GESTÃO DE ESTOQUE|GESTÃO DE TECNOLOGIA E INFORMAÇÃO EM LOGÍSTICA (GTI)|GESTÃO DE PORTUGUÊS INSTRUMENTAL|GESTÃO DE SEGURANÇA DO TRABALHO NA INDÚSTRIA E NA LOGÍSTICA'),
    $seq(-9904, 'superior-sequencial-em-gestao-hospitalar', 'Superior Sequencial em Gestão Hospitalar', 'Formação voltada ao planejamento, organização e gerenciamento de instituições hospitalares, rotinas administrativas, qualidade, auditoria, logística e equipes.', 'ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA|BIOESTATÍSTICA|COMISSÕES HOSPITALARES|CONTABILIDADE DE CUSTOS|CONTROLE E PREVENÇÃO DE INFECÇÃO HOSPITALAR|DIREITO APLICADO À GESTÃO HOSPITALAR|GESTÃO E MARKETING HOSPITALAR|AUDITORIA HOSPITALAR|CONTROLADORIA|GESTÃO HOSPITALAR E QUALIDADE NO ATENDIMENTO|PLANEJAMENTO E CONTROLADORIA FINANCEIRA|PLANEJAMENTO ESTRATÉGICO E QUALIDADE HOSPITALAR|HIGIENE E VIGILÂNCIA SANITÁRIA|LOGÍSTICA HOSPITALAR|OUVIDORIA HOSPITALAR|REGULAÇÃO, CONTROLE, AVALIAÇÃO E AUDITORIA EM SAÚDE|SISTEMAS DE INFORMAÇÃO PARA SAÚDE|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9905, 'superior-sequencial-em-gestao-financeira', 'Superior Sequencial em Gestão Financeira', 'Formação voltada à gestão financeira nas organizações, com foco em orçamento, crédito, risco, mercado financeiro, custos, controladoria e análise econômica.', 'ADMINISTRAÇÃO FINANCEIRA E CONTÁBIL|ANÁLISE DA VIABILIDADE ECONÔMICA E FINANCEIRA DE PROJETOS|ANÁLISE DE CRÉDITO E RISCO|MATEMÁTICA FINANCEIRA|MERCADO FINANCEIRO E DE CAPITAIS|ORÇAMENTO EMPRESARIAL E FLUXO DE CAIXA|PRÁTICAS FINANCEIRAS|ANÁLISE E DEMONSTRAÇÃO FINANCEIRA E BANCÁRIA|CONTROLADORIA|ECONOMIA E MERCADO GLOBAL|FINANÇAS CORPORATIVAS|FUNDAMENTOS CONTÁBEIS|ANÁLISE DAS DEMONSTRAÇÕES CONTÁBEIS|GESTÃO DE CUSTOS E FINANÇAS|GESTÃO DE RISCOS EM INVESTIMENTOS|GESTÃO TRIBUTÁRIA|GOVERNANÇA CORPORATIVA, CONTROLE INTERNO E COMPLIANCE|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9906, 'superior-sequencial-em-gestao-esportiva', 'Superior Sequencial em Gestão Esportiva', 'Formação voltada à gestão estratégica do esporte, organização esportiva, treinamento, avaliação física, marketing esportivo, liderança e equipes.', 'BIOESTATÍSTICA|EXERCÍCIO E TREINAMENTO DESPORTIVO|CONTABILIDADE DE CUSTOS|EXERCÍCIO FÍSICO E O IDOSO|PSICOLOGIA DO ESPORTE|ESTRATÉGIAS DE MARKETING|ANATOMIA HUMANA|ATLETISMO|AVALIAÇÃO FISICA DIAGNÓSTICA|BIOMECANICA DO ESPORTE|EXERCÍCIO E TREINAMENTO ESPORTIVO|FISIOLOGIA HUMANA|MEDIDAS E AVALIAÇÃO FÍSICA|FUTEBOL|LIDERANÇA E GESTÃO DE EQUIPES|GESTÃO DE SERVIÇOS DE NUTRIÇÃO E DIETÉTICA|GESTÃO DE RECURSOS HUMANOS|FUTEBOL AVANÇADO|HANDBALL|SUPLEMENTAÇAO NUTRICIONAL, RECURSOS ERGONÔMICOS E FITOTERÁPICOS NO ESPORTE|TÉCNICA DIETÉTICA BÁSICA|VOLEIBOL|FUNDAMENTOS, HISTÓRIA E FILOSOFIA DA EDUCAÇÃO FISICA|ARBITRAGEM I|ARBITRAGEM II'),
    $seq(-9907, 'superior-sequencial-em-gestao-de-pequenas-empresas', 'Superior Sequencial em Gestão de Pequenas Empresas', 'Formação voltada à administração de pequenas empresas, contemplando organização, gestão de pessoas, contratos, materiais, custos, marketing e métodos de gestão.', 'FUNDAMENTOS CONTÁBEIS|FUNDAMENTOS DE MARKETING|GESTÃO COMERCIAL|GESTÃO DA QUALIDADE|GESTÃO DE COMPRAS E NEGOCIAÇÃO|ELABORAÇÃO E GESTÃO DE CONTRATOS|GESTÃO DE DEPARTAMENTO PESSOAL|GESTÃO DE MATERIAIS|GESTÃO DE PROJETOS|GESTÃO DE STARTUPS|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|MATEMÁTICA FINANCEIRA|GESTÃO DE TIMES - MÉTODOS ÁGEIS|GESTÃO ESTRATÉGICA DE CUSTOS|GOVERNANÇA CORPORATIVA, CONTROLE INTERNO E COMPLIANCE|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9908, 'superior-sequencial-em-gestao-em-informatica', 'Superior Sequencial em Gestão em Informática', 'Formação voltada à gestão de informática, sistemas, bancos de dados, programação web, redes, segurança da informação e gestão de tecnologia.', 'AMBIENTE DE DESENVOLVIMENTO PARA WEB|INTRODUÇÃO A BANCO DE DADOS|LÓGICA DE PROGRAMAÇÃO|PORTUGUÊS INSTRUMENTAL|SEGURANÇA DA INFORMAÇÃO|MODELAGEM MATEMÁTICA|ORGANIZAÇÃO EMPRESARIAL|TECNOLOGIAS E LINGUAGENS DE BANCO DE DADOS|ANÁLISE DE MERCADO: TENDÊNCIA, COMPORTAMENTO E MOVIMENTO|GESTÃO DA TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO|GESTÃO DE TIMES - MÉTODOS ÁGEIS|INTRODUÇÃO A REDES DE COMPUTADORES E PROTOCOLOS DE COMUNICAÇÃO|LINGUAGEM DE PROGRAMAÇÃO PARA WEB (PHP)|ANÁLISE E MODELAGEM DE PROCESSOS|ANÁLISE E PROJETO DE SOFTWARE ORIENTADO A OBJETOS|GOVERNANÇA E AUDITORIA DE TECNOLOGIA DA INFORMAÇÃO|HUMAN CENTRED DESIGN|SISTEMAS DE INFORMAÇÕES GERENCIAIS|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9909, 'superior-sequencial-em-gestao-em-design-grafico', 'Superior Sequencial em Gestão em Design Gráfico', 'Formação voltada à gestão em design gráfico, criação visual, tratamento de imagens, diagramação, tecnologias de impressão e análise de mercado.', 'ANÁLISE DE MERCADO: TENDÊNCIA, COMPORTAMENTO E MOVIMENTO|HUMAN CENTRED DESIGN|ILUSTRAÇÃO E TRATAMENTO DE IMAGENS 2D - ADOBE PHOTOSHOP|PORTUGUÊS INSTRUMENTAL|SEGURANÇA, MEIO AMBIENTE, SAÚDE E RESPONSABILIDADE SOCIAL|ANÁLISE E MODELAGEM DE PROCESSOS|DIAGRAMAÇÃO DE DOCUMENTOS - ADOBE INDESIGN|ILUSTRAÇÃO E CRIAÇÃO DE IMAGENS VETORIAIS - ADOBE ILUSTRATOR|MODELAGEM MATEMÁTICA|TECNOLOGIAS DE IMPRESSÃO|ANÁLISE DA VIABILIDADE ECONÔMICA E FINANCEIRA DE PROJETOS|ANÁLISE E PESQUISA DE MERCADO|DESENHO TÉCNICO DE PLANTAS ARQUITETÔNICAS EM CAD|DIREITO DO CONSUMIDOR|ÉTICA E CIDADANIA|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9910, 'superior-sequencial-em-gestao-educacional-e-pedagogica', 'Superior Sequencial em Gestão Educacional e Pedagógica', 'Formação voltada à administração de processos educacionais, gestão escolar, políticas públicas, legislação educacional, projetos pedagógicos e tecnologias aplicadas à educação.', 'GESTÃO EDUCACIONAL|PENSAMENTO CIENTÍFICO|POLÍTICAS PÚBLICAS E EDUCAÇÃO|HISTÓRIA DA EDUCAÇÃO|GESTÃO DE RECURSOS HUMANOS E CARREIRAS|INTELIGÊNCIA ARTIFICIAL|FUNDAMENTOS DA EDUCAÇÃO|EDUCAÇÃO DAS RELAÇÕES ÉTNICO-RACIAIS|LIDERANÇA E GESTÃO DE EQUIPES|CURRÍCULOS E PROJETOS PEDAGÓGICOS|GESTÃO DE EAD|EDUCAÇÃO E TECNOLOGIAS|ORGANIZAÇÃO E LEGISLAÇÃO DA EDUCAÇÃO|PROCESSO DECISÓRIO|SEGURANÇA, MEIO AMBIENTE, SAÚDE E RESPONSABILIDADE SOCIA|DESIGN EDUCACIONAL|LIBRAS|GESTÃO DE PROJETOS|ESTRATÉGIAS DE MARKETING|ÉTICA E CIDADANIA'),
    $seq(-9911, 'superior-sequencial-em-gestao-de-vendas', 'Superior Sequencial em Gestão de Vendas', 'Formação voltada à área comercial, relacionamento com clientes, negociação, marketing, formação de preços e decisões estratégicas de vendas.', 'ANÁLISE DE MERCADO: TENDÊNCIA, COMPORTAMENTO E MOVIMENTO|FUNDAMENTOS CONTÁBEIS|FUNDAMENTOS DE MARKETING|GESTÃO DE COMPRAS E NEGOCIAÇÃO|MARKETING DE SERVIÇOS E DO VAREJO|DIREITO EMPRESARIAL|GESTÃO DA INOVAÇÃO E COMPETITIVIDADE|NEGOCIAÇÃO COMERCIAL E NEGÓCIOS ELETRÔNICOS|PORTUGUÊS INSTRUMENTAL|DIREITO DO CONSUMIDOR|DIREITO INTERNACIONAL E COMÉRCIO EXTERIOR|FORMAÇÃO DE PREÇOS|TÉCNICAS DE ATENDIMENTO E TELEATENDIMENTO AO CLIENTE|TÉCNICAS DE VENDAS|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9912, 'superior-sequencial-em-gestao-de-politicas-publicas', 'Superior Sequencial em Gestão de Políticas Públicas', 'Formação voltada às relações entre Estado e sociedade, formulação de políticas públicas, cidadania, participação, gestão pública e processos decisórios.', 'LICITAÇÕES PÚBLICAS|ADMINISTRAÇÃO PÚBLICA|POLÍTICAS PÚBLICAS E EDUCAÇÃO|EDUCAÇÃO EM DIREITOS HUMANOS|ORGANIZAÇÃO E LEGISLAÇÃO DA EDUCAÇÃO|SEGURIDADE SOCIAL – ASSISTENCIA SOCIAL|SEGURANÇA, MEIO AMBIENTE, SAÚDE E RESPONSABILIDADE SOCIAL|POLÍTICA DE SAÚDE|PROCESSO DECISÓRIO'),
    $seq(-9913, 'superior-sequencial-em-gestao-de-oficinas-mecanicas', 'Superior Sequencial em Gestão de Oficinas Mecânicas', 'Formação voltada à gestão de oficinas mecânicas e processos de manutenção, contemplando produção, materiais, qualidade, custos, contratos, equipes e organização empresarial.', 'GESTÃO DA PRODUÇÃO|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|FUNDAMENTOS DE MARKETING|ANÁLISE E MODELAGEM DE PROCESSOS|ORGANIZAÇÃO EMPRESARIAL|PLANEJAMENTO, PROGRAMAÇÃO E CONTROLE DA PRODUÇÃO|GESTÃO DE RECURSOS HUMANOS|PRÁTICAS EM CONTRATOS, REGULAMENTOS E NORMATIVAS|LIDERANÇA E GESTÃO DE EQUIPES|GESTÃO DE MATERIAIS|GESTÃO DA TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO|GESTÃO DA QUALIDADE|GESTÃO DA INOVAÇÃO E COMPETITIVIDADE|FORMAÇÃO DE PREÇOS|GESTÃO DE CUSTOS E FINANÇAS|MATEMÁTICA FINANCEIRA'),
    $seq(-9914, 'superior-sequencial-em-gestao-de-negocios', 'Superior Sequencial em Gestão de Negócios', 'Formação voltada à administração de negócios, processos empresariais, contratos, materiais, custos, projetos, qualidade e organização estratégica.', 'FUNDAMENTOS CONTÁBEIS|FUNDAMENTOS DE MARKETING|GESTÃO COMERCIAL|GESTÃO DA QUALIDADE|GESTÃO DE COMPRAS E NEGOCIAÇÃO|ANÁLISE E MODELAGEM DE PROCESSO|ELABORAÇÃO E GESTÃO DE CONTRATOS|GESTÃO DE DEPARTAMENTO PESSOAL|GESTÃO DE MATERIAIS|GESTÃO DE PROJETOS|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|MATEMÁTICA FINANCEIRA|GESTÃO DE TIMES - MÉTODOS ÁGEIS|GESTÃO ESTRATÉGICA DE CUSTOS|GOVERNANÇA CORPORATIVA, CONTROLE INTERNO E COMPLIANCE|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9915, 'superior-sequencial-em-gestao-de-minimercados', 'Superior Sequencial em Gestão de Minimercados', 'Formação voltada à gestão de minimercados, pequenos negócios do varejo alimentar, organização de setores, categorias, produção, materiais, custos e qualidade.', 'GESTÃO DA PRODUÇÃO|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|FUNDAMENTOS DE MARKETING|ANÁLISE E MODELAGEM DE PROCESSOS|ORGANIZAÇÃO EMPRESARIAL|PLANEJAMENTO, PROGRAMAÇÃO E CONTROLE DA PRODUÇÃO|GESTÃO DE RECURSOS HUMANOS|PRÁTICAS EM CONTRATOS, REGULAMENTOS E NORMATIVAS|LIDERANÇA E GESTÃO DE EQUIPES|GESTÃO DE MATERIAIS|GESTÃO DA TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO|GESTÃO DA QUALIDADE|GESTÃO DA INOVAÇÃO E COMPETITIVIDADE|FORMAÇÃO DE PREÇOS|CONTABILIDADE DE CUSTOS|MATEMÁTICA FINANCEIRA'),
    $seq(-9916, 'superior-sequencial-em-gestao-de-marketing', 'Superior Sequencial em Gestão de Marketing', 'Formação voltada ao marketing tático e administrativo, com foco em composto de marketing, serviços, varejo, eventos, métricas, propaganda, preço e relacionamento comercial.', 'ADMINISTRAÇÃO FINANCEIRA E CONTÁBIL|ANÁLISE DE MERCADO: TENDÊNCIA, COMPORTAMENTO E MOVIMENTO|GESTÃO DA INOVAÇÃO E COMPETITIVIDADE|GESTÃO DA QUALIDADE|MARKETING DE SERVIÇOS E DO VAREJO|ESTRATÉGIAS DE MARKETING|MARKETING DE EVENTOS|MÉTRICAS DE MARKETING|NEGOCIAÇÃO COMERCIAL E NEGÓCIOS ELETRÔNICOS|PUBLICIDADE E PROPAGANDA|ESTUDOS AVANÇADOS DE MARKETING SUSTENTÁVEL|FORMAÇÃO DE PREÇOS|MARKETING ELETRÔNICO E INTERNACIONAL|MARKETING PESSOAL E GESTÃO DE CARREIRA|TRADE MARKETING|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9917, 'superior-sequencial-em-gestao-de-laboratorios-clinicos', 'Superior Sequencial em Gestão de Laboratórios Clínicos', 'Formação voltada à gestão de serviços laboratoriais, processos em saúde, biossegurança, sistemas de informação, auditoria e gerenciamento de riscos.', 'GESTÃO DE RISCOS|GESTÃO DE SERVIÇOS LABORATORIAIS E SETORES ESPECIALIZADOS|BIOÉTICA E BIOSSEGURANÇA|SISTEMAS DE INFORMAÇÃO PARA A SAÚDE|GESTÃO DO PROCESSO E DA FORÇA DE TRABALHO EM SAÚDE|MODELOS E GESTÃO DE SERVIÇOS EM SAÚDE|REGULAÇÃO, CONTROLE, AVALIAÇÃO E AUDITORIA EM SAÚDE|BIOESTATÍSTICA|GERENCIAMENTO DE PERIGOS E RISCOS À SAÚDE (GPRS)'),
    $seq(-9918, 'superior-sequencial-em-gestao-de-instituicoes-religiosas', 'Superior Sequencial em Gestão de Instituições Religiosas', 'Formação voltada à administração, assessoria, planejamento e condução de atividades em instituições de cunho social ou religioso.', 'FILOSOFIA DA RELIGIAO|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|PSICOLOGIA E ESPIRITUALIDADE|TEORIA DO CONHECIMENTO E FILOSOFIA DA CIÊNCIA|ORGANIZAÇÃO EMPRESARIAL|ESTRATÉGIAS DE MARKETING|GESTÃO DE RECURSOS HUMANOS|PRÁTICAS EM CONTRATOS, REGULAMENTOS E NORMATIVAS|LIDERANÇA E GESTÃO DE EQUIPES|ORATORIA|GESTÃO DA TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO|GESTÃO DA QUALIDADE|ESCRITA FISCAL E LEGISLAÇÃO TRIBUTÁRIA|ELABORAÇÃO E GESTÃO DE CONTRATOS|CONTABILIDADE DE CUSTOS'),
    $seq(-9919, 'superior-sequencial-em-gestao-de-futebol', 'Superior Sequencial em Gestão de Futebol', 'Formação voltada à gestão do futebol de base e profissional, com foco em clubes, entidades esportivas, treinamento, avaliação, marketing, arbitragem e equipes.', 'FUNDAMENTOS, HISTÓRIA E FILOSOFIA DA EDUCAÇÃO FISICA|FUTEBOL|FUTEBOL AVANÇADO|BIOESTATÍSTICA|EXERCÍCIO E TREINAMENTO DESPORTIVO|CONTABILIDADE DE CUSTOS|EXERCÍCIO FÍSICO E O IDOSO|PSICOLOGIA DO ESPORTE|ESTRATÉGIAS DE MARKETING|ANATOMIA HUMANA|TÉCNICA DIETÉTICA BÁSICA|AVALIAÇÃO FISICA DIAGNÓSTICA|BIOMECANICA DO ESPORTE|EXERCÍCIO E TREINAMENTO ESPORTIVO|FISIOLOGIA HUMANA|MEDIDAS E AVALIAÇÃO FÍSICA|LIDERANÇA E GESTÃO DE EQUIPES|GESTÃO DE SERVIÇOS DE NUTRIÇÃO E DIETÉTICA|GESTÃO DE RECURSOS HUMANOS|SUPLEMENTAÇAO NUTRICIONAL, RECURSOS ERGONÔMICOS E FITOTERÁPICOS NO ESPORTE|ARBITRAGEM I|ARBITRAGEM II'),
    $seq(-9920, 'superior-sequencial-em-gestao-de-franquias', 'Superior Sequencial em Gestão de Franquias', 'Formação voltada ao planejamento estratégico de franquias, análise de mercado, competitividade, custos, marketing, vendas, negociação e gestão de equipes.', 'DIVISÃO E MODELAGEM DE CARGOS E SALÁRIOS|ADMINISTRAÇÃO FINANCEIRA E CONTÁBIL|ANÁLISE DA VIABILIDADE ECONÔMICA E FINANCEIRA DE PROJETOS|ANÁLISE E PESQUISA DE MERCADO|ESTRATÉGIAS DE MARKETING|GESTÃO DA INOVAÇÃO E COMPETITIVIDADE|CONTABILIDADE DE CUSTOS|ORÇAMENTO EMPRESARIAL E FLUXO DE CAIXA|GESTÃO COMERCIAL|GESTÃO DA INOVAÇÃO E COMPETITIVIDADE|MARKETING E PROPAGANDA DIGITAL|TÉCNICAS DE VENDAS|MATEMÁTICA FINANCEIRA|MARKETING E PROPAGANDA DIGITAL|TRADE MARKETING|NEGOCIAÇÃO COMERCIAL E NEGÓCIOS ELETRÔNICOS|GESTÃO DE DEPARTAMENTO PESSOAL|LIDERANÇA E GESTÃO DE EQUIPES'),
    $seq(-9921, 'superior-sequencial-em-gestao-de-farmacias', 'Superior Sequencial em Gestão de Farmácias', 'Formação voltada à gestão de farmácias, serviços farmacêuticos, operação de loja, custos, estoques, suprimentos, riscos e força de trabalho em saúde.', 'GESTÃO DA QUALIDADE|GESTÃO DE CUSTOS, RISCOS E PERDAS - GCRP|GESTÃO DE ESTOQUE|GESTÃO DE SERVIÇOS DE FARMÁCIA|GESTÃO DE SUPRIMENTOS E LOGÍSTICA EMPRESARIAL|GESTÃO DO PROCESSO E DA FORÇA DE TRABALHO EM SAÚDE|REGULAÇÃO, CONTROLE, AVALIAÇÃO E AUDITORIA EM SAÚDE|GESTÃO OPERACIONAL DE LOJA'),
    $seq(-9922, 'superior-sequencial-em-gestao-de-empresas', 'Superior Sequencial em Gestão de Empresas', 'Formação voltada à teoria geral da administração, processos de gerência, estruturas empresariais, qualidade, contratos, materiais, projetos, custos e recursos humanos.', 'AUDITORIA DA QUALIDADE|FUNDAMENTOS CONTÁBEIS|FUNDAMENTOS DE MARKETING|GESTÃO DA QUALIDADE|GESTÃO DE COMPRAS E NEGOCIAÇÃO|ANÁLISE E MODELAGEM DE PROCESSOS|ELABORAÇÃO E GESTÃO DE CONTRATOS|GESTÃO DE DEPARTAMENTO PESSOAL|GESTÃO DE MATERIAIS|GESTÃO DE PROJETOS|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|FERRAMENTAS DA QUALIDADE|GESTÃO DE TIMES|GESTÃO ESTRATÉGICA DE CUSTOS|GOVERNANÇA CORPORATIVA, CONTROLE INTERNO E COMPLIANCE|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9923, 'superior-sequencial-em-gestao-de-comercio-exterior', 'Superior Sequencial em Gestão de Comércio Exterior', 'Formação voltada a comércio exterior, globalização, integração econômica, Mercosul, câmbio, financiamento, logística internacional e negociação comercial.', 'DIREITO DIGITAL|DIREITO INTERNACIONAL E COMÉRCIO EXTERIOR|GESTÃO COMERCIAL|NEGOCIAÇÃO COMERCIAL E NEGÓCIOS ELETRÔNICOS|TÉCNICAS DE ATENDIMENTO E TELEATENDIMENTO AO CLIENTE|DIREITO DO CONSUMIDOR|ECONOMIA E MERCADO GLOBAL|ESCRITA FISCAL E LEGISLAÇÃO TRIBUTÁRIA|ÉTICA E CIDADANIA|FUNDAMENTOS DE MARKETING|FORMAÇÃO DE PREÇOS|LOGÍSTICA INTERNACIONAL|MARKETING ELETRÔNICO E INTERNACIONAL|GESTÃO DE RISCOS EM INVESTIMENTOS|INGLÊS INSTRUMENTAL-SEM CONTEUDO|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9924, 'superior-sequencial-em-gestao-de-arbitragem', 'Superior Sequencial em Gestão de Arbitragem', 'Formação voltada à arbitragem no futebol, regras, imparcialidade, controle de partida, fundamentos esportivos, treinamento, avaliação física e gestão de equipes.', 'FUNDAMENTOS, HISTÓRIA E FILOSOFIA DA EDUCAÇÃO FISICA|ARBITRAGEM I|ARBITRAGEM II|FUTEBOL|FUTEBOL AVANÇADO|BIOESTATÍSTICA|EXERCÍCIO E TREINAMENTO DESPORTIVO|CONTABILIDADE DE CUSTOS|EXERCÍCIO FÍSICO E O IDOSO|PSICOLOGIA DO ESPORTE|ESTRATÉGIAS DE MARKETING|ANATOMIA HUMANA|TÉCNICA DIETÉTICA BÁSICA|AVALIAÇÃO FISICA DIAGNÓSTICA|BIOMECANICA DO ESPORTE|EXERCÍCIO E TREINAMENTO ESPORTIVO|FISIOLOGIA HUMANA|MEDIDAS E AVALIAÇÃO FÍSICA|LIDERANÇA E GESTÃO DE EQUIPES|GESTÃO DE SERVIÇOS DE NUTRIÇÃO E DIETÉTICA|GESTÃO DE RECURSOS HUMANOS|SUPLEMENTAÇAO NUTRICIONAL, RECURSOS ERGONÔMICOS E FITOTERÁPICOS NO ESPORTE'),
    $seq(-9925, 'superior-sequencial-em-gestao-da-seguranca-publica-e-privada', 'Superior Sequencial em Gestão da Segurança Pública e Privada', 'Formação voltada à segurança pública e privada, políticas de segurança, cidadania, organizações de segurança, processos, projetos, qualidade e gestão de equipes.', 'ADMINISTRAÇÃO PÚBLICA|ANÁLISE E MODELAGEM DE PROCESSOS|FINANÇAS CORPORATIVAS|GESTÃO DA QUALIDADE|GESTÃO DE COMPRAS E NEGOCIAÇÃO|ELABORAÇÃO E GESTÃO DE CONTRATOS|GESTÃO DE DEPARTAMENTO PESSOAL|GESTÃO DE MATERIAIS|GESTÃO DE PROJETOS|POLÍTICAS DE SEGURANÇA PÚBLICA|ESTRATÉGIAS DE GESTÃO E ORGANIZAÇÃO EMPRESARIAL|GESTÃO DA TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO|GESTÃO DE EQUIPES|GESTÃO DE RECURSOS HUMANOS|MEIO AMBIENTE E QUALIDADE DE VIDA'),
    $seq(-9926, 'superior-sequencial-em-gestao-da-producao-de-conteudo-para-midias-digitais', 'Superior Sequencial em Gestão da Produção de Conteúdo para Mídias Digitais', 'Formação voltada à produção de conteúdo para mídias digitais, redes sociais, revistas digitais, usabilidade, imagens, infográficos, textos visuais e engajamento.', 'ANÁLISE DE MERCADO: TENDÊNCIA, COMPORTAMENTO E MOVIMENTO|HUMAN CENTRED DESIGN|ILUSTRAÇÃO E TRATAMENTO DE IMAGENS 2D - ADOBE PHOTOSHOP|PORTUGUÊS INSTRUMENTAL|SEGURANÇA, MEIO AMBIENTE, SAÚDE E RESPONSABILIDADE SOCIAL|ANÁLISE E MODELAGEM DE PROCESSOS|DIAGRAMAÇÃO DE DOCUMENTOS - ADOBE INDESIGN|ILUSTRAÇÃO E CRIAÇÃO DE IMAGENS VETORIAIS - ADOBE ILUSTRATOR|MODELAGEM MATEMÁTICA|TECNOLOGIAS DE IMPRESSÃO|ANÁLISE DA VIABILIDADE ECONÔMICA E FINANCEIRA DE PROJETOS|ANÁLISE E PESQUISA DE MERCADO|DIREITO DO CONSUMIDOR|GESTÃO DA PRODUÇÃO|SISTEMAS E MULTIMÍDIA|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9927, 'superior-sequencial-em-gestao-em-contabilidade', 'Superior Sequencial em Gestão em Contabilidade', 'Formação voltada à contabilidade, auditoria, demonstrações financeiras, tributos, orçamento, controladoria, crédito, risco, custos e governança.', 'CONTABILIDADE INTERMEDIÁRIA|ECONOMIA E MERCADO GLOBAL|GESTÃO TRIBUTÁRIA|MATEMÁTICA FINANCEIRA|NOÇÕES DE DIREITO|ANÁLISE DAS DEMONSTRAÇÕES CONTÁBEIS|CONTABILIDADE DE CUSTOS|CONTROLADORIA|FINANÇAS CORPORATIVAS|ORÇAMENTO EMPRESARIAL E FLUXO DE CAIXA|ANÁLISE DE CRÉDITO E RISCO|ANÁLISE E DEMONSTRAÇÃO FINANCEIRA E BANCÁRIA|GESTÃO DE CUSTOS E FINANÇAS|GESTÃO DE RISCOS EM INVESTIMENTOS|GOVERNANÇA CORPORATIVA, CONTROLE INTERNO E COMPLIANCE|GESTÃO DE RECURSOS HUMANOS'),
    $seq(-9928, 'superior-sequencial-em-gestao-da-construcao-civil', 'Superior Sequencial em Gestão da Construção Civil', 'Formação voltada à gestão da construção civil, projetos, obras, orçamento, controle, sistemas construtivos, topografia, segurança, qualidade e sustentabilidade.', 'ANÁLISE E MODELAGEM DE PROCESSOS|FUNDAMENTOS DA CONSTRUÇÃO CIVIL|MODELAGEM MATEMÁTICA|PORTUGUÊS INSTRUMENTAL|SEGURANÇA, MEIO AMBIENTE, SAÚDE E RESPONSABILIDADE SOCIAL|ANÁLISE DA VIABILIDADE ECONÔMICA E FINANCEIRA DE PROJETOS|DESENHO TÉCNICO DE PLANTAS ARQUITETÔNICAS EM CAD|DIREITO DO CONSUMIDOR|ÉTICA E CIDADANIA|SEGURANÇA DO TRABALHO NA CONSTRUÇÃO CIVIL-NR18|GESTÃO DE PROJETOS|PLANEJAMENTO, ORÇAMENTO E CONTROLE DE OBRAS|GESTÃO DE RECURSOS HUMANOS|SISTEMAS E PROCESSOS CONSTRUTIVOS|PROJETOS DE EDIFICAÇÕES|TOPOGRAFIA'),
];
