<?php
declare(strict_types=1);

$groups = [
    'Direito' => [
        'Direito de Família e Sucessões',
        'Compliance',
        'Direito Contábil',
        'Direito Digital',
        'Informática Forense',
        'Direito Eleitoral',
        'Direito Penal e Processual Penal',
        'Direito Tributário e Processual Tributário',
        'Direito Previdenciário',
        'Direito do Trabalho e Processual Trabalhista',
        'Direito Constitucional',
        'Direito Civil e Processual Civil',
        'Direito Empresarial',
        'Direito dos Novos Negócios',
        'Direito Contratual',
        'Direito Internacional',
        'Direito Aduaneiro',
        'Direito Imobiliário',
        'Direito Notarial e Registral',
        'Segurança Pública e Política Criminal',
        'Direito Educacional',
        'Direito Ambiental',
        'Direito Público Licitatório',
        'Direito Público Constitucional, Administrativo e Tributário',
        'Direito Administrativo',
        'Direito LGBT+',
    ],
    'Saúde e bem-estar' => [
        'Análises Clínicas e Diagnóstico Laboratorial',
        'Atenção e Cuidados com Idosos',
        'Atendimento na Unidade Básica de Saúde',
        'Atendimento na Unidade Básica de Saúde - Enfermagem',
        'Atendimento na Unidade Básica de Saúde - Farmácia',
        'Atendimento na Unidade Básica de Saúde - Nutrição',
        'Cuidados Básicos em Hospitais Municipais',
        'Enfermagem do Trabalho',
        'Enfermagem do Trabalho e Saúde Ocupacional',
        'Enfermagem Oncológica',
        'Estética e Cosmetologia',
        'Farmacologia Clínica',
        'Fisioterapia Aplicada às Atividades Físicas',
        'Fisioterapia em Geriatria e Gerontologia',
        'Fitoterapia e Suplementação Nutricional',
        'Nutrição Clínica',
        'Nutrição e Dietética',
        'Nutrição Esportiva',
        'Segurança do Paciente e Gestão dos Riscos Assistenciais',
    ],
    'Psicologia' => [
        'Avaliação Psicológica e Psicodiagnóstico',
        'Neuropsicopedagogia',
        'Psicologia Hospitalar',
        'Psicologia do Trânsito',
    ],
    'Engenharia' => [
        'Engenharia de Produção',
        'Engenharia de Negócios',
        'Engenharia Econômica e Financeira',
        'Engenharia de Suprimentos',
        'Engenharia Logística',
        'Indústria 4.0',
        'Engenharia Ambiental',
        'Engenharia Ambiental e Energias Renováveis',
        'Engenharia Ambiental e Saneamento Básico',
        'Engenharia de Segurança do Trabalho',
        'Engenharia de Software',
        'Engenharia Elétrica',
        'Engenharia de Redes e Segurança de Dados',
        'Engenharia da Qualidade',
        'Engenharia da Manutenção',
    ],
    'Tecnologia e comunicação' => [
        'Desenvolvimento Web',
        'Desenvolvimento Mobile',
        'Análise e Projeto de Software',
        'Web Design',
        'Administração de Redes',
        'Administração de Dados',
        'Administração de Servidores Linux',
        'Administração de Servidores Windows',
        'Segurança da Informação',
        'Ciência de Dados',
        'Internet das Coisas',
        'Inteligência Artificial',
        'Sistemas de Informações Gerenciais',
    ],
    'Educação' => [
        'Educação 5.0',
        'Tutoria em Educação a Distância',
        'Educação a Distância',
        'Educação Infantil',
        'Educação Corporativa',
        'Neuroeducação',
        'Psicopedagogia Escolar',
        'Alfabetização e Letramento',
        'Educação Inclusiva e Diversidade',
        'Educação Inclusiva',
        'Transtornos e Problemas na Aprendizagem',
        'Educação e Direitos Humanos',
        'Educação Financeira',
        'Educação Ambiental e Sustentabilidade',
        'Projetos Pedagógicos',
        'Coordenação Educacional',
        'Supervisão e Orientação Escolar',
        'Supervisão e Orientação Escolar em Educação Infantil',
        'Educação de Jovens e Adultos',
        'Psicomotricidade',
        'Metodologias Ativas e Tecnologias Educacionais',
        'Tecnologias Educacionais',
        'Secretariado Escolar',
        'Letramento e Produção de Textos para o Ensino Fundamental',
        'Ensino da Língua Portuguesa',
        'Ensino da Literatura e Produção de Textos em Língua Portuguesa',
        'Ensino da Língua Inglesa',
        'Ensino da Literatura e Produção de Textos em Língua Inglesa',
        'Ensino da Língua Espanhola',
        'Ensino da Literatura e Produção de Textos em Língua Espanhola',
        'Letras com Ênfase em Linguística',
        'Ensino de Ciências',
        'Ensino de História',
        'Ensino de Artes',
        'Ensino de Geografia',
        'Ensino de Matemática',
        'Psicomotricidade e Educação Especial',
        'Alfabetização, Letramento e Psicopedagogia',
        'Coordenação e Orientação Escolar',
        'LIBRAS - Língua Brasileira de Sinais',
        'Língua Portuguesa - Redação e Oratória',
        'Ensino da História e Geografia',
        'Ensino da Língua Portuguesa e Literatura',
        'Metodologia do Ensino Superior nas Várias Modalidades',
        'Psicopedagogia em Educação Especial',
        'Psicomotricidade na Educação Infantil',
    ],
    'Serviço Social' => [
        'Perícia Social',
        'Serviço Social no Terceiro Setor',
        'Serviço Social na Saúde',
        'Serviço Social na Educação',
        'Serviço Social na Administração Pública',
    ],
    'MBA' => [
        'MBA em Administração Pública',
        'MBA em Auditoria Contábil',
        'MBA em Contabilidade Gerencial',
        'MBA em Controladoria Financeira',
        'MBA em Finanças Corporativas e Controladoria',
        'MBA em Gestão Financeira e Contábil',
        'MBA em Gestão de Startups',
        'MBA em Gestão de Pessoas e Talentos',
        'MBA em Gestão Estratégica de Pessoas',
        'MBA em Gestão Estratégica e Inovação',
        'MBA em Gestão de Pessoal e Pagadoria',
        'MBA em Liderança e Desenvolvimento de Pessoas',
        'MBA em Gestão da Tecnologia da Informação',
        'MBA em Gestão da Tecnologia da Informação e Comunicação',
        'MBA em Empreendedorismo e Marketing',
        'MBA em Gestão do Processo de Inovação',
        'MBA em Gestão Estratégica de Marketing',
        'MBA em Gestão de Marketing Digital',
        'MBA em Gestão de Marketing Político',
        'MBA em Gestão Ambiental',
        'MBA em Gestão Ambiental Sustentável',
        'MBA em Gestão da Cadeia de Suprimentos',
        'MBA em Gestão da Logística Empresarial',
        'MBA em Gestão de Processos',
        'MBA em Gestão de Processos da Produção',
        'MBA em Gestão da Produção',
        'MBA em Gestão de Projetos',
        'MBA em Gestão de Supply Chain',
        'MBA em Gestão Empresarial',
        'MBA em Gestão em Construção Civil',
        'MBA em Gestão e Orientação Escolar',
        'MBA em Gestão Educacional',
        'MBA em Gestão Educacional Pública',
        'MBA em Gestão da Saúde',
        'MBA em Gestão da Saúde Municipal',
        'MBA em Gestão de Farmácias',
        'MBA em Gestão de Farmácias e Drogarias',
        'MBA em Gestão de Hospitais',
        'MBA em Gestão de Pandemias',
        'MBA em Gestão de Unidades Oncológicas',
        'MBA em Gestão de Serviços Laboratoriais',
        'MBA em Gestão em Saúde Pública',
        'MBA em Gestão Farmacêutica',
        'MBA em Gestão Hospitalar',
        'MBA em Gestão Jurídica',
        'MBA em Gestão Pública',
        'MBA em Gestão Social',
        'MBA em Gestão Social Estratégica',
        'MBA em Modelagem e Gestão de Processos',
        'MBA em Perícia e Auditoria Contábil',
        'MBA em Gestão de Planejamento e Gestão no Trânsito',
    ],
];

$products = [];
$id = -12000;
$seen = [];

foreach ($groups as $area => $courses) {
    foreach ($courses as $courseName) {
        $baseTitle = trim($courseName);
        $title = str_starts_with($baseTitle, 'MBA em') ? $baseTitle : 'Especialização em ' . $baseTitle;
        $slug = ibetp_slug_key('pos-graduacao-' . $title);
        if (isset($seen[$slug])) {
            continue;
        }
        $seen[$slug] = true;
        $id--;
        $category = 'Pós-graduação e MBA';
        $isMba = str_starts_with($title, 'MBA em');
        $kind = $isMba ? 'MBA lato sensu' : 'Pós-graduação lato sensu';
        $short = $title . '. ' . $kind . ' EAD, com titulação de Especialista, duração de 4 a 12 meses e carga horária de 400 a 800 horas, conforme informativo acadêmico.';
        $products[] = [
            'id' => $id,
            'slug' => $slug,
            'title' => $title,
            'category' => $category,
            'area' => $area === 'MBA' ? 'Gestão e negócios' : $area,
            'price' => 799.00,
            'currency' => 'BRL',
            'checkout_enabled' => 1,
            'status' => 'active',
            'duration' => '4 a 12 meses',
            'workload' => '400 a 800 horas',
            'image' => '',
            'short_description' => $short,
            'description' => $short . ' O IBETP realiza atendimento consultivo para matrícula, documentação e próximos passos acadêmicos, sem expor contatos de instituições parceiras.',
            'seo_title' => $title . ' | IBETP',
            'seo_description' => $title . ' EAD no IBETP: investimento, documentos, modalidade, duração e funcionamento acadêmico para matrícula segura.',
            'updated_at' => '2026-07-21 00:00:00',
            'academic' => [
                'duration' => '4 a 12 meses',
                'workload' => '400 a 800 horas',
                'modality_note' => 'Modalidade EAD, com a maior parte do conteúdo disponibilizada por videoaulas gravadas, trilhas de aprendizagem e materiais digitais.',
                'presence' => 'Modalidade EAD com estudo online, materiais digitais, avaliações e acompanhamento acadêmico pelo ambiente de aprendizagem.',
                'internship' => '',
                'tcc' => '',
                'source' => 'Informativo oficial de Pós-Graduação disponibilizado ao IBETP.',
                'curriculum_note' => '',
                'modules' => [],
            ],
        ];
    }
}

return $products;
